CREATE TABLE ads_terraqt_ecmwf_ens_by_station_v (
    station_code VARCHAR(5),
    province VARCHAR(20),
    city VARCHAR(40),
    district VARCHAR(40),
    coordinates VARCHAR(40),
    date_time DATETIME,
    version DATETIME,
    temperature_2m DOUBLE NULL,
    dewpoint_2m DOUBLE NULL,
    pressure_surface DOUBLE NULL,
    apparent_temperature DOUBLE NULL,
    humidity DOUBLE NULL,
    cloudcover DOUBLE NULL,
    cloudcover_low DOUBLE NULL,
    cloudcover_medium DOUBLE NULL,
    cloudcover_high DOUBLE NULL,
    windspeed_10m DOUBLE NULL,
    windspeed_100m DOUBLE NULL,
    windspeed_200m DOUBLE NULL,
    precipitation_instant DOUBLE NULL,
    shortwave_radiation_instant DOUBLE NULL,
    snow_fall_instant DOUBLE NULL,
    total_precipitation DOUBLE NULL,
    shortwave_radiation DOUBLE NULL,
    snow_fall DOUBLE NULL COMMENT '累计降雪量， 单位米',
    PRIMARY KEY (version, date_time, station_code)
);
